### ISSUE TITLE
add dashboardaddWidgetsToPage and dashboardUpdatePage support in dashboards

### ISSUE THREAD

**Issue by smcavallo** [newrelic/newrelic-client-go#802]
### Feature Description
Add support for these missing operations to dashboards
https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/dashboards-api/#page-operations
`dashboardUpdatePage()`
`dashboardUpdateWidgetsInPage()`
`dashboardAddWidgetsToPage()`
and the additional type of `DashboardUpdatePageInput`

It may be as simple as adding to `.tutone.yaml`
```
    mutations:
      - name: dashboardAddWidgetsToPage
      - name: dashboardUpdatePage
      - name: dashboardUpdateWidgetsInPage
```

### Describe Alternatives
These are all available in the nerdgraph API and in fact exist in the schema.json file created when you run `make generate` - they just don't exist in `.tutone.yaml` or `dashboards_api.go`

### Additional context
I tried to add support for this myself in `.tutone.yaml`  but `make generate` does not work locally - it is generating the types incorrectly and then failing due to errors in the types.  It is using the default version of the tutone generator which is tagged as "dev"
